version: '3.4'

x-common-variables: &commonvars
  GST_DEBUG : webrtcbin:7

services:
  turnserver:
    image: "coturn/coturn:4.5.2-r7-debian"
    environment:
      <<: *commonvars
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    command:
      - --log-file=stdout
      - --external-ip=${PUBLIC_HOST:-127.0.0.1}  
      - --min-port=65000
      - --max-port=65535

  signaling:
    image: "gstreamer-python:latest"
    environment:
      <<: *commonvars
    volumes:
      - ./:/src
    command: bash -c "cd /src && echo RUN SOCKETIO server"

  peer1:
    image: "gstreamer-python:latest"
    depends_on:
      - signaling
      - turnserver
    environment:
      <<: *commonvars
      WEBRTC_STUN_SERVER: ${STUN_SERVER_URL:-stun://turnserver:3478}
      WEBRTC_TURN_SERVER: turn://turnserver:3478?transport=udp
    volumes:
      - ./:/src
    command: bash -c "cd /src && echo RUN PEER1"

  peer2:
    image: "gstreamer-python:latest"
    depends_on:
      - signaling
      - turnserver
    environment:
      <<: *commonvars
      WEBRTC_STUN_SERVER: ${STUN_SERVER_URL:-stun://turnserver:3478}
      WEBRTC_TURN_SERVER: turn://turnserver:3478?transport=udp
    volumes:
      - ./:/src
    command: bash -c "cd /src && echo RUN PEER2"
